name: CI
on: [push, pull_request]
jobs:
  format-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format Markdown with markdownlint
        run: |
          npm install -g markdownlint-cli
          markdownlint --disable MD013 MD033 --fix . --ignore CODE_OF_CONDUCT.md
          git add -A
          git diff --cached --exit-code
  test-and-coverage:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # to support `git describe`
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: './go.mod'
    - name: Test
      run: make tests
    - name: Build CLI app
      run: make build_cli
    - name: Coveralls (ubuntu-latest only)
      if: matrix.os == 'ubuntu-latest'
      uses: coverallsapp/github-action@v2
